Script fix 160

diff --git a/.github/workflows/aa_workflow23.yaml b/.github/workflows/aa_workflow23.yaml
--- a/.github/workflows/aa_workflow23.yaml
+++ b/.github/workflows/aa_workflow23.yaml
@@ -1,13 +1,37 @@
-name: UsageOfcheckoutAction
-on: [push, workflow_dispatch]
+name: status check functions
+on: [push, pull_request,workflow_dispatch]
+
 jobs:
-  UsageOfcheckoutAction:
+  job-1:
     runs-on: ubuntu-latest
     steps:
-      - name: files before checkout
-        run: ls -l
-      - name: Check out action
-        id: Checkout
-        uses: actions/checkout@v3
-      - name: files after checkout
-        run: ls -l
+      - name: Steps -1 
+        run: sleep 20
+      - name: steps-2
+        id: steps2
+        run: exit 1
+      - name: Runs on failure
+        # if: failure()
+        if: steps.steps2.conclusion == 'failure'
+        run: echo "Runs on only failure"
+      - name: Runs on success
+        # this is not required. By default
+        if: success()
+        run: echo "Runs on only Success"
+      - name: Always runs
+        # this is not required. By default  if: suceess() || failure()
+        if: Always()  
+        run: echo "Runs always"
+      - name: Runs on cancelled
+        if: cancelled()
+        run: echo " Runs when cancelled" 
+
+  job-2:
+    runs-on: ubuntu-latest
+    needs: job-1
+    if: failure()
+    steps:
+      - name: Job-2
+        run: echo "Job-2 run"
+      
+      
